# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-27 19:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_buddy', '0002_travel'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='traveler',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='travels', to='travel_buddy.User'),
            preserve_default=False,
        ),
    ]
