# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-27 19:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_buddy', '0003_travel_traveler'),
    ]

    operations = [
        migrations.CreateModel(
            name='Travler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='travel',
            name='traveler',
        ),
        migrations.AddField(
            model_name='travler',
            name='travler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travels', to='travel_buddy.Travel'),
        ),
        migrations.AddField(
            model_name='travler',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traveler', to='travel_buddy.User'),
        ),
    ]
